AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: awslambdasourcebucketnew
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: awslambdadestinationbucketnew