AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: my-group-name
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess # Example policy, change as needed

        